// Court Craft drill library, carried over from the shipped build.
//
// equipment is the MINIMUM needed:
//   none  -> nothing but space
//   ball  -> a ball
//   hoop  -> a ball and a hoop
//   court -> a full court
//   gym   -> a court and a weight room

export type Focus =
  | 'ball-handling' | 'shooting' | 'finishing'
  | 'defense' | 'athleticism' | 'conditioning';

export type Equipment = 'none' | 'ball' | 'hoop' | 'court' | 'gym';

export type Drill = {
  id: string;
  name: string;
  focus: Focus;
  equipment: Equipment;
  /** Authored length of one round of this drill, in minutes. */
  minutes: number;
  /** What to actually do. */
  work: string;
  /** The one thing to think about while doing it. */
  cue?: string;
  positions: string[];
};

export const DRILLS: Drill[] = [
  {
    id: 'behind-back-series',
    name: 'Behind-the-Back Series',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 4,
    work: '3 x 30 sec each direction',
    cue: 'Wrap it around your hip, not your back. Keep walking forward.',
    positions: ['all'],
  },
  {
    id: 'cone-attack',
    name: 'Cone Attack Series',
    focus: 'ball-handling',
    equipment: 'court',
    minutes: 6,
    work: '4 lengths, a different move at each cone',
    cue: 'Attack the cone shoulder-first. Do not slow down into the move.',
    positions: ['all'],
  },
  {
    id: 'scissors',
    name: 'Continuous Between the Legs',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 3,
    work: '3 x 30 sec each lead foot',
    cue: 'Push it through, do not lob it. Stay square to the rim.',
    positions: ['all'],
  },
  {
    id: 'crossover-series',
    name: 'Crossover Series',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 5,
    work: '4 x 30 sec: front, between legs, behind back',
    cue: 'Sell it with your shoulders, not just your hands.',
    positions: ['all'],
  },
  {
    id: 'tennis-ball-toss',
    name: 'Dribble with Tennis Ball Toss',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 4,
    work: '3 x 45 sec each hand',
    cue: 'Forces your eyes off the ball. That is the whole point.',
    positions: ['all'],
  },
  {
    id: 'figure-eight',
    name: 'Figure-8 Wraps',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 3,
    work: '3 x 30 sec, switch directions',
    cue: 'Fingertips, not palms. Widen your base as you speed up.',
    positions: ['all'],
  },
  {
    id: 'full-court-handles',
    name: 'Full-Court Handle at Speed',
    focus: 'ball-handling',
    equipment: 'court',
    minutes: 6,
    work: '6 lengths, one move per length',
    cue: 'Game speed. If you never lose it, you are not going hard enough.',
    positions: ['all'],
  },
  {
    id: 'hesitation-series',
    name: 'Hesitation and Go',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 4,
    work: '3 x 8 each hand',
    cue: 'Rise slightly, pause a beat, then explode. The pause is the move.',
    positions: ['all'],
  },
  {
    id: 'low-pound',
    name: 'Low Pound Dribble',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 3,
    work: '3 x 30 sec each hand, ball below the knee',
    cue: 'Sit into your hips. The lower it is, the harder it is to steal.',
    positions: ['all'],
  },
  {
    id: 'one-hand-control',
    name: 'One-Hand Control Dribble',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 3,
    work: '3 x 30 sec each hand, no switching',
    cue: 'Keep it alive with one hand only. Builds the weak hand fastest.',
    positions: ['all'],
  },
  {
    id: 'pull-back-crossover',
    name: 'Pull-Back Crossover',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 4,
    work: '3 x 10 each hand',
    cue: 'Retreat two hard dribbles, then cross. Space first, then go.',
    positions: ['all'],
  },
  {
    id: 'retreat-dribble',
    name: 'Retreat Dribble',
    focus: 'ball-handling',
    equipment: 'court',
    minutes: 5,
    work: '6 reps each hand, half court',
    cue: 'Back out under control with the ball on your back hip.',
    positions: ['all'],
  },
  {
    id: 'spider-dribble',
    name: 'Spider Dribble',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 3,
    work: '3 x 30 sec',
    cue: 'Front hand, front hand, back hand, back hand. Small and fast.',
    positions: ['all'],
  },
  {
    id: 'pound-dribble',
    name: 'Stationary Pound Dribble',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 3,
    work: '3 x 30 sec each hand',
    cue: 'Pound below the knee. Eyes up the whole time.',
    positions: ['all'],
  },
  {
    id: 'two-ball-alternating',
    name: 'Two-Ball Alternating Dribble',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 4,
    work: '3 x 30 sec',
    cue: 'One ball up as the other goes down. Rhythm before speed.',
    positions: ['all'],
  },
  {
    id: 'two-ball-crossover',
    name: 'Two-Ball Crossovers',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 4,
    work: '3 x 30 sec',
    cue: 'Cross both at once, low and in front of your knees.',
    positions: ['all'],
  },
  {
    id: 'two-ball-in-out',
    name: 'Two-Ball In-and-Out',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 4,
    work: '3 x 30 sec',
    cue: 'Fake the cross with your wrist. The ball stays in the same hand.',
    positions: ['all'],
  },
  {
    id: 'two-ball-pound',
    name: 'Two-Ball Pound Dribble',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 4,
    work: '3 x 30 sec',
    cue: 'Both balls hit the floor together. Stay in an athletic stance.',
    positions: ['all'],
  },
  {
    id: 'wall-taps',
    name: 'Wall Ball Taps',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 3,
    work: '3 x 30 sec, fingertips only',
    cue: 'Arms extended, tap it off the wall. Builds grip and touch.',
    positions: ['all'],
  },
  {
    id: 'wide-pound',
    name: 'Wide Pound Dribble',
    focus: 'ball-handling',
    equipment: 'ball',
    minutes: 3,
    work: '3 x 30 sec each hand, ball outside your frame',
    cue: 'Push it outside your foot and pull it back under control.',
    positions: ['all'],
  },
  {
    id: 'zig-zag-dribble',
    name: 'Zig-Zag Change of Direction',
    focus: 'ball-handling',
    equipment: 'court',
    minutes: 6,
    work: '6 lengths of the court',
    cue: 'Plant hard on the outside foot. Push off, do not drift.',
    positions: ['all'],
  },
  {
    id: 'beat-the-pro',
    name: 'Beat the Pro',
    focus: 'shooting',
    equipment: 'hoop',
    minutes: 8,
    work: 'First to 11. You score 1 per make, the pro scores 2 per miss',
    cue: 'A game with a consequence. Shoot it like it counts.',
    positions: ['all'],
  },
  {
    id: 'catch-turn-shoot',
    name: 'Catch, Turn and Shoot',
    focus: 'shooting',
    equipment: 'hoop',
    minutes: 6,
    work: '10 makes each side',
    cue: 'Catch facing away, turn on the inside foot, shoot in one motion.',
    positions: ['all'],
  },
  {
    id: 'spot-shooting',
    name: 'Catch-and-Shoot, Five Spots',
    focus: 'shooting',
    equipment: 'none',
    minutes: 10,
    work: '50 shots, 10 from each of five spots',
    positions: ['all'],
  },
  {
    id: 'corner-threes',
    name: 'Corner Threes',
    focus: 'shooting',
    equipment: 'none',
    minutes: 6,
    work: '40 shots, 20 from each corner',
    positions: ['all'],
  },
  {
    id: 'curl-off-screen',
    name: 'Curl Off Screen Shooting',
    focus: 'shooting',
    equipment: 'court',
    minutes: 8,
    work: '10 makes each side',
    cue: 'Hands ready before you come off. Chin over the inside shoulder.',
    positions: ['all'],
  },
  {
    id: 'elbow-jumpers',
    name: 'Elbow Jumpers',
    focus: 'shooting',
    equipment: 'none',
    minutes: 7,
    work: '40 shots, 20 from each elbow',
    positions: ['all'],
  },
  {
    id: 'off-screen-fade',
    name: 'Fade Off Screen',
    focus: 'shooting',
    equipment: 'court',
    minutes: 7,
    work: '8 makes each side',
    cue: 'Read the defender. If they chase over the top, fade away from it.',
    positions: ['all'],
  },
  {
    id: 'fade-away',
    name: 'Fadeaway Series',
    focus: 'shooting',
    equipment: 'hoop',
    minutes: 6,
    work: '6 makes each shoulder',
    cue: 'Fade straight back, not sideways. Higher arc to beat the length.',
    positions: ['all'],
  },
  {
    id: 'form-shooting',
    name: 'Form Shooting',
    focus: 'shooting',
    equipment: 'hoop',
    minutes: 6,
    work: '50 makes, close to the rim',
    cue: 'One hand guides, one hand rides. Hold your follow-through.',
    positions: ['all'],
  },
  {
    id: 'free-throws',
    name: 'Free Throws',
    focus: 'shooting',
    equipment: 'none',
    minutes: 5,
    work: '5 sets of 10',
    positions: ['all'],
  },
  {
    id: 'hop-into-three',
    name: 'Hop-Into Three',
    focus: 'shooting',
    equipment: 'hoop',
    minutes: 7,
    work: '8 makes from each of five spots',
    cue: 'Hop into the catch so your feet land already set.',
    positions: ['all'],
  },
  {
    id: 'midrange-five-spot',
    name: 'Midrange Five Spots',
    focus: 'shooting',
    equipment: 'none',
    minutes: 9,
    work: '50 shots from the elbows, wings and free throw line',
    positions: ['all'],
  },
  {
    id: 'pull-up-one-dribble',
    name: 'One-Dribble Pull-Up',
    focus: 'shooting',
    equipment: 'hoop',
    minutes: 8,
    work: '8 makes each direction, 5 spots',
    cue: 'Gather low, rise straight up. Do not drift sideways.',
    positions: ['all'],
  },
  {
    id: 'one-hand-form',
    name: 'One-Hand Form Shooting',
    focus: 'shooting',
    equipment: 'hoop',
    minutes: 5,
    work: '3 x 10 makes, guide hand behind your back',
    cue: 'Exposes everything wrong with your release. Elbow under the ball.',
    positions: ['all'],
  },
  {
    id: 'pressure-free-throws',
    name: 'Pressure Free Throws',
    focus: 'shooting',
    equipment: 'none',
    minutes: 5,
    work: '25 shots, sprint a length after every miss',
    positions: ['all'],
  },
  {
    id: 'relocation-shooting',
    name: 'Relocation Shooting',
    focus: 'shooting',
    equipment: 'hoop',
    minutes: 7,
    work: '10 makes, moving to a new spot after each',
    cue: 'Never stand still after a pass. Relocate, then be ready.',
    positions: ['all'],
  },
  {
    id: 'shot-fake-pull-up',
    name: 'Shot Fake, One Dribble, Pull-Up',
    focus: 'shooting',
    equipment: 'hoop',
    minutes: 7,
    work: '8 makes each direction',
    cue: 'Sell the fake with your eyes and the ball, not your feet.',
    positions: ['all'],
  },
  {
    id: 'side-step-three',
    name: 'Side-Step Three',
    focus: 'shooting',
    equipment: 'hoop',
    minutes: 6,
    work: '6 makes each direction',
    cue: 'Slide along the arc to dodge the closeout. Stay behind the line.',
    positions: ['all'],
  },
  {
    id: 'step-back',
    name: 'Step-Back Series',
    focus: 'shooting',
    equipment: 'hoop',
    minutes: 7,
    work: '6 makes each direction',
    cue: 'Create the space with your feet before you go up.',
    positions: ['all'],
  },
  {
    id: 'three-point-spots',
    name: 'Three-Point Spot Shooting',
    focus: 'shooting',
    equipment: 'none',
    minutes: 10,
    work: '100 shots, 20 from each of five spots',
    positions: ['all'],
  },
  {
    id: 'transition-threes',
    name: 'Transition Threes',
    focus: 'shooting',
    equipment: 'court',
    minutes: 7,
    work: '8 makes, sprinting into each shot',
    cue: 'Sprint the lane, then set your feet. The legs must be under you.',
    positions: ['all'],
  },
  {
    id: 'baby-hook',
    name: 'Baby Hook',
    focus: 'finishing',
    equipment: 'hoop',
    minutes: 5,
    work: '10 makes each hand',
    cue: 'Off the inside foot with a straight arm. Nearly unblockable.',
    positions: ['all'],
  },
  {
    id: 'contact-finish',
    name: 'Contact Finishes',
    focus: 'finishing',
    equipment: 'hoop',
    minutes: 6,
    work: '6 makes each side',
    cue: 'Absorb the bump, then finish. Land balanced on two feet.',
    positions: ['all'],
  },
  {
    id: 'drop-step-hook',
    name: 'Drop Step to Jump Hook',
    focus: 'finishing',
    equipment: 'hoop',
    minutes: 6,
    work: '8 makes each shoulder',
    cue: 'Feel the defender, then seal. Shoot over the opposite shoulder.',
    positions: ['all'],
  },
  {
    id: 'euro-step',
    name: 'Euro Step Finishes',
    focus: 'finishing',
    equipment: 'hoop',
    minutes: 6,
    work: '8 makes each direction',
    cue: 'Long first step, longer second. Sell the first direction.',
    positions: ['all'],
  },
  {
    id: 'face-up-drive',
    name: 'Face-Up Drive',
    focus: 'finishing',
    equipment: 'hoop',
    minutes: 6,
    work: '6 makes each direction from the elbow',
    cue: 'Face up, read the feet, one hard dribble to the rim.',
    positions: ['all'],
  },
  {
    id: 'floater',
    name: 'Floater Series',
    focus: 'finishing',
    equipment: 'hoop',
    minutes: 6,
    work: '10 makes each side',
    cue: 'High and soft, off one foot, before the big man commits.',
    positions: ['all'],
  },
  {
    id: 'transition-finish',
    name: 'Full-Speed Transition Finish',
    focus: 'finishing',
    equipment: 'court',
    minutes: 7,
    work: '10 makes, full court each rep',
    cue: 'Finish at the speed you actually play at, not at walking pace.',
    positions: ['all'],
  },
  {
    id: 'inside-hand-finish',
    name: 'Inside Hand Finish',
    focus: 'finishing',
    equipment: 'hoop',
    minutes: 5,
    work: '8 makes each side',
    cue: 'Finish with the hand furthest from the defender, high off the glass.',
    positions: ['all'],
  },
  {
    id: 'mikan',
    name: 'Mikan Drill',
    focus: 'finishing',
    equipment: 'hoop',
    minutes: 4,
    work: '2 x 1 min continuous',
    cue: 'Never let the ball hit the floor. Use the glass.',
    positions: ['all'],
  },
  {
    id: 'outside-hand-finish',
    name: 'Outside Hand Finish',
    focus: 'finishing',
    equipment: 'hoop',
    minutes: 5,
    work: '8 makes each side',
    cue: 'Extend away from the help and lay it in soft off the corner.',
    positions: ['all'],
  },
  {
    id: 'pro-hop',
    name: 'Pro Hop',
    focus: 'finishing',
    equipment: 'hoop',
    minutes: 5,
    work: '8 makes each side',
    cue: 'Two hands on the ball through the hop, or it is a travel.',
    positions: ['all'],
  },
  {
    id: 'reverse-layup',
    name: 'Reverse Layup Series',
    focus: 'finishing',
    equipment: 'hoop',
    minutes: 5,
    work: '8 makes each side',
    cue: 'Cross under and finish on the far side. The rim protects the ball.',
    positions: ['all'],
  },
  {
    id: 'reverse-mikan',
    name: 'Reverse Mikan',
    focus: 'finishing',
    equipment: 'hoop',
    minutes: 4,
    work: '2 x 1 min continuous',
    cue: 'Keep the rim between you and an imaginary defender.',
    positions: ['all'],
  },
  {
    id: 'spin-finish',
    name: 'Spin Move Finish',
    focus: 'finishing',
    equipment: 'hoop',
    minutes: 5,
    work: '6 makes each direction',
    cue: 'Spin off the front foot and keep the ball tight to your chest.',
    positions: ['all'],
  },
  {
    id: 'two-foot-finish',
    name: 'Two-Foot Power Finish',
    focus: 'finishing',
    equipment: 'hoop',
    minutes: 5,
    work: '8 makes each side',
    cue: 'Gather on two feet and jump straight up. Balance beats speed here.',
    positions: ['all'],
  },
  {
    id: 'up-and-under',
    name: 'Up-and-Under',
    focus: 'finishing',
    equipment: 'hoop',
    minutes: 5,
    work: '6 makes each shoulder',
    cue: 'Fake the hook, step through under the arm, finish soft.',
    positions: ['all'],
  },
  {
    id: 'hands-active',
    name: 'Active Hands and Digs',
    focus: 'defense',
    equipment: 'ball',
    minutes: 4,
    work: '3 x 45 sec in stance',
    cue: 'Hands moving without reaching. Mirror the ball, do not grab at it.',
    positions: ['all'],
  },
  {
    id: 'box-out',
    name: 'Box-Out and Rebound',
    focus: 'defense',
    equipment: 'hoop',
    minutes: 5,
    work: '3 x 10 reps',
    cue: 'Find the body first, then the ball. Chin the rebound.',
    positions: ['all'],
  },
  {
    id: 'closeout',
    name: 'Closeout and Contest',
    focus: 'defense',
    equipment: 'court',
    minutes: 6,
    work: '10 reps each side',
    cue: 'Sprint the first half, chop your feet the second. High hand.',
    positions: ['all'],
  },
  {
    id: 'closeout-contest-rebound',
    name: 'Closeout, Contest, Rebound',
    focus: 'defense',
    equipment: 'court',
    minutes: 7,
    work: '8 full reps',
    cue: 'The rep is not over at the contest. Find a body and finish it.',
    positions: ['all'],
  },
  {
    id: 'slide-ladder',
    name: 'Defensive Slide Ladder',
    focus: 'defense',
    equipment: 'court',
    minutes: 6,
    work: '5 rounds, baseline to free throw line and back',
    cue: 'Never cross your feet. Push off the trail leg.',
    positions: ['all'],
  },
  {
    id: 'stance-hold',
    name: 'Defensive Stance Hold',
    focus: 'defense',
    equipment: 'ball',
    minutes: 3,
    work: '3 x 45 sec',
    cue: 'Chest up, hips down, weight on the balls of your feet.',
    positions: ['all'],
  },
  {
    id: 'deny-stance',
    name: 'Denial Stance and Jump to the Ball',
    focus: 'defense',
    equipment: 'court',
    minutes: 5,
    work: '3 x 45 sec',
    cue: 'Hand in the lane, eyes on man and ball. Move on the pass.',
    positions: ['all'],
  },
  {
    id: 'drop-step-slide',
    name: 'Drop Step and Slide',
    focus: 'defense',
    equipment: 'court',
    minutes: 5,
    work: '8 reps each direction',
    cue: 'Open the gate with a drop step, then recover to square.',
    positions: ['all'],
  },
  {
    id: 'help-and-recover',
    name: 'Help and Recover',
    focus: 'defense',
    equipment: 'court',
    minutes: 6,
    work: '8 reps each side',
    cue: 'Two steps in to help, sprint back out on the pass.',
    positions: ['all'],
  },
  {
    id: 'lateral-slide-mirror',
    name: 'Mirror Slides',
    focus: 'defense',
    equipment: 'ball',
    minutes: 5,
    work: '4 x 30 sec, mirroring a partner or a line',
    cue: 'React, do not anticipate. Stay chest to chest.',
    positions: ['all'],
  },
  {
    id: 'post-defense',
    name: 'Post Defence and Fronting',
    focus: 'defense',
    equipment: 'hoop',
    minutes: 6,
    work: '8 reps each side',
    cue: 'Beat them to the seal. Front early rather than wrestle late.',
    positions: ['all'],
  },
  {
    id: 'rebound-tip',
    name: 'Rebound Tip Drill',
    focus: 'defense',
    equipment: 'hoop',
    minutes: 4,
    work: '3 x 30 sec continuous tips off the glass',
    cue: 'Tip with your fingers at the top of your jump. Do not come down.',
    positions: ['all'],
  },
  {
    id: 'sprint-to-help',
    name: 'Sprint to the Help Line',
    focus: 'defense',
    equipment: 'court',
    minutes: 5,
    work: '10 reps',
    cue: 'On every pass you move. Defence is the running you do off the ball.',
    positions: ['all'],
  },
  {
    id: 'zig-zag-defense',
    name: 'Zig-Zag Defensive Slides',
    focus: 'defense',
    equipment: 'court',
    minutes: 6,
    work: '4 lengths of the court',
    cue: 'Force them to the sideline and keep beating them to the spot.',
    positions: ['all'],
  },
  {
    id: 'a-skips',
    name: 'A-Skips',
    focus: 'athleticism',
    equipment: 'ball',
    minutes: 3,
    work: '4 x 20 metres',
    cue: 'Tall posture, knee up, foot strikes under your hip.',
    positions: ['all'],
  },
  {
    id: 'approach-jumps',
    name: 'Approach Jumps',
    focus: 'athleticism',
    equipment: 'hoop',
    minutes: 5,
    work: '5 x 5, full rest between sets',
    cue: 'Two hard steps into the jump. Reach as high as you can.',
    positions: ['all'],
  },
  {
    id: 'box-jump',
    name: 'Box Jump',
    focus: 'athleticism',
    equipment: 'gym',
    minutes: 5,
    work: '5 x 5, step down between reps',
    cue: 'Step down, never jump down. The landing is the injury risk.',
    positions: ['all'],
  },
  {
    id: 'split-squat',
    name: 'Bulgarian Split Squat',
    focus: 'athleticism',
    equipment: 'gym',
    minutes: 6,
    work: '3 x 8 each leg',
    cue: 'Front knee tracks over the toe. Control the way down.',
    positions: ['all'],
  },
  {
    id: 'copenhagen',
    name: 'Copenhagen Plank',
    focus: 'athleticism',
    equipment: 'gym',
    minutes: 4,
    work: '3 x 20 sec each side',
    cue: 'Groin strength, which is where guards tend to break down.',
    positions: ['all'],
  },
  {
    id: 'depth-drop',
    name: 'Depth Drop Landing',
    focus: 'athleticism',
    equipment: 'gym',
    minutes: 4,
    work: '4 x 5 from a low box',
    cue: 'Drop off, land soft and freeze. Teaches you to absorb force.',
    positions: ['all'],
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    focus: 'athleticism',
    equipment: 'gym',
    minutes: 6,
    work: '3 x 10',
    cue: 'Chest tall, knees out, sit between your hips.',
    positions: ['all'],
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    focus: 'athleticism',
    equipment: 'gym',
    minutes: 6,
    work: '3 x 10',
    cue: 'Drive through the heels and squeeze at the top. Ribs down.',
    positions: ['all'],
  },
  {
    id: 'lateral-bounds',
    name: 'Lateral Bounds',
    focus: 'athleticism',
    equipment: 'ball',
    minutes: 4,
    work: '4 x 10 each side',
    cue: 'Stick the landing for a full second before you go back.',
    positions: ['all'],
  },
  {
    id: 'med-ball-slam',
    name: 'Medicine Ball Slam',
    focus: 'athleticism',
    equipment: 'gym',
    minutes: 4,
    work: '4 x 8',
    cue: 'Whole body into it. Reach tall, then drive it into the floor.',
    positions: ['all'],
  },
  {
    id: 'nordic-curl',
    name: 'Nordic Hamstring Curl',
    focus: 'athleticism',
    equipment: 'gym',
    minutes: 5,
    work: '3 x 5, slow negatives',
    cue: 'Resist the whole way down. This is injury insurance.',
    positions: ['all'],
  },
  {
    id: 'calf-pogos',
    name: 'Pogo Hops',
    focus: 'athleticism',
    equipment: 'ball',
    minutes: 3,
    work: '3 x 20',
    cue: 'Ankles only, knees nearly locked. Minimum ground contact.',
    positions: ['all'],
  },
  {
    id: 'single-leg-rdl',
    name: 'Single-Leg RDL',
    focus: 'athleticism',
    equipment: 'gym',
    minutes: 5,
    work: '3 x 8 each leg',
    cue: 'Hinge at the hip with a flat back. Balance is part of the drill.',
    positions: ['all'],
  },
  {
    id: 'skater-hops',
    name: 'Skater Hops',
    focus: 'athleticism',
    equipment: 'ball',
    minutes: 4,
    work: '4 x 10 each side',
    cue: 'Push sideways off one leg and land balanced on the other.',
    positions: ['all'],
  },
  {
    id: 'squat-jumps',
    name: 'Squat Jumps',
    focus: 'athleticism',
    equipment: 'ball',
    minutes: 4,
    work: '4 x 8',
    cue: 'Land quiet and absorb. Quality over quantity.',
    positions: ['all'],
  },
  {
    id: 'broad-jump',
    name: 'Standing Broad Jump',
    focus: 'athleticism',
    equipment: 'ball',
    minutes: 4,
    work: '5 x 3, full rest',
    cue: 'Swing the arms, land soft and stick it. Measure it if you can.',
    positions: ['all'],
  },
  {
    id: 'calf-raises',
    name: 'Weighted Calf Raises',
    focus: 'athleticism',
    equipment: 'gym',
    minutes: 4,
    work: '3 x 15, full range',
    cue: 'All the way down, all the way up, pause at the top.',
    positions: ['all'],
  },
  {
    id: 'seventeens',
    name: '17s',
    focus: 'conditioning',
    equipment: 'court',
    minutes: 8,
    work: '4 rounds: 17 sideline touches in 60 sec',
    cue: 'Pace the first six. Do not die on the last four.',
    positions: ['all'],
  },
  {
    id: 'bike-intervals',
    name: 'Bike or Rower Intervals',
    focus: 'conditioning',
    equipment: 'gym',
    minutes: 8,
    work: '8 x 30 sec hard, 60 sec easy',
    cue: 'All the engine, none of the pounding. Good on sore legs.',
    positions: ['all'],
  },
  {
    id: 'continuous-layups',
    name: 'Continuous Layups',
    focus: 'conditioning',
    equipment: 'hoop',
    minutes: 6,
    work: '3 x 90 sec, alternating sides',
    cue: 'Never stop moving. Rebound your own and go straight back.',
    positions: ['all'],
  },
  {
    id: 'slide-conditioning',
    name: 'Defensive Slide Conditioning',
    focus: 'conditioning',
    equipment: 'court',
    minutes: 6,
    work: '6 x 30 sec continuous slides, 30 sec rest',
    cue: 'Stance the whole interval. Standing up is quitting early.',
    positions: ['all'],
  },
  {
    id: 'dynamic-warmup',
    name: 'Dynamic Warm-Up',
    focus: 'conditioning',
    equipment: 'ball',
    minutes: 5,
    work: 'High knees, butt kicks, leg swings, hip openers',
    cue: 'Move through a full range. Do not stretch cold and hold.',
    positions: ['all'],
  },
  {
    id: 'full-court-layups',
    name: 'Full-Court Layup Sprints',
    focus: 'conditioning',
    equipment: 'court',
    minutes: 7,
    work: '10 lengths, finishing each one',
    cue: 'Conditioning you can actually use. Make the layup tired.',
    positions: ['all'],
  },
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    focus: 'conditioning',
    equipment: 'ball',
    minutes: 5,
    work: '5 x 1 min, 30 sec rest',
    cue: 'Stay on the balls of your feet. Small, fast turns.',
    positions: ['all'],
  },
  {
    id: 'suicides',
    name: 'Line Drills (Suicides)',
    focus: 'conditioning',
    equipment: 'court',
    minutes: 8,
    work: '6 rounds, 45 sec rest',
    cue: 'Touch every line with your hand. No shortcuts.',
    positions: ['all'],
  },
  {
    id: 'ladder-quick-feet',
    name: 'Quick Feet Ladder',
    focus: 'conditioning',
    equipment: 'ball',
    minutes: 4,
    work: '6 patterns, down and back',
    cue: 'Light and fast beats big and slow. Eyes up, not on your feet.',
    positions: ['all'],
  },
  {
    id: 'shuttle-runs',
    name: 'Shuttle Runs',
    focus: 'conditioning',
    equipment: 'court',
    minutes: 6,
    work: '8 x 5-10-5, 45 sec rest',
    cue: 'The turn is the drill. Get low and change direction hard.',
    positions: ['all'],
  },
  {
    id: 'sprint-intervals',
    name: 'Sprint Intervals',
    focus: 'conditioning',
    equipment: 'ball',
    minutes: 7,
    work: '10 x 20 sec sprint, 40 sec walk',
    cue: 'Full speed on every rep or it is not a sprint.',
    positions: ['all'],
  },
  {
    id: 'stair-sprints',
    name: 'Stair Sprints',
    focus: 'conditioning',
    equipment: 'ball',
    minutes: 7,
    work: '8 climbs, walk down to recover',
    cue: 'Drive the knees. Walk down every time, never run down.',
    positions: ['all'],
  },
  {
    id: 'tempo-runs',
    name: 'Tempo Runs',
    focus: 'conditioning',
    equipment: 'ball',
    minutes: 8,
    work: '6 x 100 metres at three quarter speed',
    cue: 'Relaxed and smooth. Builds the base that lets you recover.',
    positions: ['all'],
  },
];
